version: '3'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data

  dev-xdebug:
    build:
      context: docker/xdebug
      args:
        IMAGE: phpstan-phpunit-dev
    volumes:
      - ./:/code
      - ./data:/data
